<section>
    <h1>Página Inicial</h1>
</section>
<section>
    <h1>Guêro</h1>
    <div class="cont">
            <div class="item"></div>
            <div class="item"></div>
            <div class="item"></div>
            <div class="item"></div>
            <div class="item"></div>
            <div class="item"></div>
            <div class="item"></div>
            <div class="item"></div>
    </div>
</section>